### ISSUE TITLE
Change updated courses (minor corrections)

### ISSUE THREAD

**Issue by kelvindecosta** [bpdc-acm/openlib.cs#4]
The following courses require the minor corrections:

*   [Object Oriented Programming](../tree/master/courses/CSF213)
*   [Logic in Computer Science](../tree/master/courses/CSF214)
*   [Operating Systems](../tree/master/courses/CSF372)
*   [Cryptography](../tree/master/courses/CSF463)
*   [Service Oriented Computing](../tree/master/courses/CSF466)

Most of the changes required are related to markdown linting.

**Comment by Mohammed-Shoaib** [comment]
I updated the above courses to follow a desired format as given by the created [template](../tree/master/TEMPLATE.md). 

All the above courses have now been corrected to follow the format.
